name: Building XML2RDF and testing

on: 
  schedule:
    - cron: '0 0 * * SAT'
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false

    - name: Build
      run: cargo build --verbose

  end-to-end:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false

    - name: Run Rust integration tests
      run: cargo test

